### ISSUE TITLE
Internal server error when creating the database

### ISSUE THREAD

**Issue by sicknessquick** [bobintetley/asm3#1082]
Hello.

I'm trying to set up a new instance of asm3 on an online hosting after doing several tests on . I've tried both Debian (11 and 10) and Ubuntu (20.04).

I install Apache, MariaDB, PHP and PHPMyAdmin and then ASM3. 

Then when I access the app with my browser, it redirects me to the database creation page. After clicking Create Database it runs for a bit until showing an internal server error. 

Checking the database with phpmyadmin shows the last table created is stockusagetype, with all of them being empty. 

<img src="https://i.imgur.com/B4stMYr.png">

This only happens on instances in my hosting service. I've previously made several tests on local virtual machines in my computer and it didn't happen. Just to see what would happen, I exported the full database from one of those working virtual machines and imported it on my online instance. I could access asm3, but it would again show an internal server error when trying to create a new animal, or when trying to access the config page... 

Can anyone help me find the cause and maybe fix it? I'm not the most experienced guy with this kind of thing, and it's making me crazy.

Thanks in advance.

**Comment by bobintetley** [comment]
Hi, please do not report bugs when you want support - particularly when it's clear that your problem is environmental and not a fault with the software.

The forum is here:   https://sheltermanager.com/site/en_forum.html

Include info from your apache logs - the actual error will be reported there when Apache returns internal server error. It will probably be /var/log/apache/error.log but it depends if you are using a vhost as to which file the logs go into.
