### ISSUE TITLE
Option to uninstall, reset reinstall ASM to get to a fresh start needed

### ISSUE THREAD

**Issue by winecraft** [bobintetley/asm3#123]
Hi Bob,
 
In trying to get it working my install is messed up. **How can I reinstall, my install and the permissions on Ubuntu 16.04 (WSGI and Apache) Desktop is fully corrupted?** I keep getting the forbidden error or internal server error - there is something wrong in the configuration listed.

1. Also, if possible it would help to have the `$PYTHONPATH` as part of the configuration in the default-site `WSGIPythonPath`, this can pick up the [correct **version** and **path**](http://stackoverflow.com/questions/12931013/wsgipythonpath-is-not-working), rather than  hard-coding it.
2. I switched over to Apache2, by following _stop the sheltermanager3 service running and remove it from the existing system runlevels:_  can I still run on the local server? from you snippet you provided earlier?
```
/etc/init.d/sheltermanager3 stop
update-rc.d sheltermanager3 remove
```
3. I did a [chgroup and chown ](http://bit.ly/2iRGyI0), how can I reset this back - or how to reinstall with fresh default options
```
chmod +x /usr
chmod +x /usr/lib
chmod -R +x /usr/lib/sheltermanager
```
4. Yes the options on the main wiki page for configuration and the sitedef.py don't match, running a simple Ctrl+F shows they are missing

Any chance of getting the MySql Maria Create DB Script?

thanks
Ollie

**Comment by bobintetley** [comment]
If you want to reinstall, remove and reinstall the deb package - apt-get remove sheltermanager3

If you don't know what you're doing with WSGI that's fine, but it's not an ASM issue and I can only be of limited help with Apache.

You're welcome to set WSGIPythonPath, but you only need to reference the code.py script with WSGIScriptAlias and ASM discovers its own path and adds it to sys.path at runtime so you don't need to set it manually. If you're seeing Internal Server Error and Forbidden, go look in the Apache logs (/var/log/apache/error.log) to find out what the problem is.

Where's the main wiki page so I can get that fixed? The DB_* variables certainly should be in sitedefs.py as the application would not compile and run if they weren't there.

Have you tried the cron.py script? Assuming you've got sitedefs.py set to an empty database, you can do:

cd /usr/lib/sheltermanager3
python cron.py maint_db_install

To do the full database install against the target database. All SQL should be logged to the console too so you can capture it. If you just run python cron.py, it has other functions for resetting and reloading databases.
