### ISSUE TITLE
Vaccinations administered by vet

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#220]
We should have a report similar to "Vaccinations administered between two dates", which shows the exact same data (vacces given) but with a grouping on the administering vet and a count for each one.

**Comment by Tetzor** [comment]
Hmm counting sheltercode does seem to work OK looking at the test I did 
so I guess my understanding is wrong, let me know if looks OK and I will 
push

**Comment by Tetzor** [comment]
Hey bro

I just knocked together this one and then when I ran it to check I 
noticed the other tables don't have borders so I will remove them after 
if you want. Have a look when you get chance, I'm not sure what should 
go in the tables.

Im also thinking you will want a new row in the table for each date 
something is given rather than 1/5 in status column? if so im struggling 
to do it, if not then great!
