### ISSUE TITLE
Can not upload photo on app

### ISSUE THREAD

**Issue by Bambiemurphy** [bobintetley/asm3#257]
Since the last update at ASM it will no longer let us update, take photos on our tablet.

**Comment by bobintetley** [comment]
Please contact support with issues rather than creating application bugs - this is not detailed or specific enough for a bug report. Let us know which model tablet you have, how you are accessing ASM (web browser or the sheltermanager app) and how you are trying to take photos - are you using the normal interface or the dedicated app photo uploader?
