### ISSUE TITLE
Picture Resolution 

### ISSUE THREAD

**Issue by nellanaesp** [bobintetley/asm3#276]
The picture resolution, when viewing things from the media tab of an animal, is awful. We have screenshots of notes from our old system we are putting in, but when we click the picture we can't read anything.

**Comment by bobintetley** [comment]
Hi, is this a sheltermanager.com account or a self hosted installation? The resolution that newly uploaded images are scaled to can be set in the configuration table on self-hosted installations. Notes and documents should generally not be uploaded as images due to photos being scaled down and PDFs should be used instead as there are no limits on those.

**Comment by nellanaesp** [comment]
It's a sheltermanager.com account.

**Comment by bobintetley** [comment]
Ok, would you mind emailing support at support@sheltermanager.com with the account number so we can take a look please? github issues are for bugs and development issues with the open source software rather than support. Thanks.
