### ISSUE TITLE
Search error when searching for unfiltered text

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#377]
Using the top search form results in an error with any text that's typed into it.  This seems to only occur when no filters are applied.
```
Traceback (most recent call last):, referer: https://drifter.bloomington.in.gov/main?noreload=1
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 239, in process, referer: https://drifter.bloomington.in.gov/main?noreload=1
    return self.handle(), referer: https://drifter.bloomington.in.gov/main?noreload=1
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 230, in handle, referer: https://drifter.bloomington.in.gov/main?noreload=1
    return self._delegate(fn, self.fvars, args), referer: https://drifter.bloomington.in.gov/main?noreload=1
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 462, in _delegate, referer: https://drifter.bloomington.in.gov/main?noreload=1
    return handle_class(cls), referer: https://drifter.bloomington.in.gov/main?noreload=1
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 438, in handle_class, referer: https://drifter.bloomington.in.gov/main?noreload=1
    return tocall(*args), referer: https://drifter.bloomington.in.gov/main?noreload=1
  File "/srv/sites/asm/src/code.py", line 293, in GET, referer: https://drifter.bloomington.in.gov/main?noreload=1
    c = self.controller(o), referer: https://drifter.bloomington.in.gov/main?noreload=1
  File "/srv/sites/asm/src/code.py", line 4674, in controller, referer: https://drifter.bloomington.in.gov/main?noreload=1
    results, timetaken, explain, sortname = extsearch.search(o.dbo, o.session, q), referer: https://drifter.bloomington.in.gov/main?noreload=1
  File "/srv/sites/asm/src/search.py", line 402, in search, referer: https://drifter.bloomington.in.gov/main?noreload=1
    sortresults = sorted(results, reverse=True, key=lambda k: k["SORTON"]), referer: https://drifter.bloomington.in.gov/main?noreload=1
TypeError: can't compare datetime.datetime to NoneType, referer: https://drifter.bloomington.in.gov/main?noreload=1, referer: https://drifter.bloomington.in.gov/main?noreload=1
```

![search](https://user-images.githubusercontent.com/630282/36447349-2365b7ea-1652-11e8-9c33-3b51cd25021e.png)

**Comment by bobintetley** [comment]
Well, that's interesting. This is not an error I've seen in production. k["SORTON"] should be holding the sort value. The fact that's comparing datetime to None suggests that it's doing the "Most Recently Changed" sort and you must somehow have a null value in the LastChangedDate column of a record. That's not normally possible!

**Comment by inghamn** [comment]
```sql
select count(*) from animal where lastchangeddate is null;
```
```
 count 
-------
     0
(1 row)
```

**Comment by bobintetley** [comment]
Oh. Could you find out which of the searches it is that's failing? Try prefixing with one of a: p: la: fa: ac: li: until you get the error. Something is definitely a null that shouldn't be :)

**Comment by inghamn** [comment]
The prefixes (a: p: la: fa: ac: li: ) all work okay.  It's when you don't use a prefix that it errors.

**Comment by bobintetley** [comment]
Oh, I missed wl: 

I still think the original diagnosis is correct. If you append sort:az instead of using the most recent sort on last changed date, does that stop it occurring? Did you check lastchangeddate for null animalcontrol, owner, animallost and animalfound?

As well as a null in LASTCHANGEDDATE in all those records, a null in ownerlicence.ISSUEDATE when searching licenses would produce the same error. I think that one has a not null constraint on it though where lastchangeddate doesn't, but never should be.

**Comment by inghamn** [comment]
Okay, found the tables;
```
select count(*) from animalcontrol where lastchangeddate is null;
 count 
-------
 61137

select count(*) from owner where lastchangeddate is null;
 count 
-------
 36166
```

We migrated from MySQL to Postgres during this release. So, I reviewed the tables from our MySQL installation.  They were null there as well.  So, these were not getting set correctly during normal operations?
```
mysql> select count(*) from animalcontrol where LastChangedDate is null;
+----------+
| count(*) |
+----------+
|    61137 |
+----------+
1 row in set (0.07 sec)

mysql> select count(*) from owner where LastChangedDate is null;
+----------+
| count(*) |
+----------+
|    36167 |
+----------+
1 row in set (0.04 sec)
```

**Comment by bobintetley** [comment]
They weren't? Search shouldn't have worked on MySQL either and it would have looked weird when using the system since the created and last changed dates are shown in the banner on most records. Was any kind of transformation done before the import? Maybe a column manipulation that involved copying the table and those columns were left off or something? I have no idea how they could have become null and if there was a bug that wasn't setting them, we'd surely have seen it in production?

**Comment by inghamn** [comment]
I'm pretty sure these were imported from our old system when we switched to sheltermanager.  We've had these bad records the whole time, as far as I can tell.

I think search was "working" on MySQL - or at least not erroring out. It may be due to MySQL's difference in date types or null value handling.

Would it be worthwhile to add a NOT NULL DEFAULT CURRENT_DATE to these lastchangeddate fields, to prevent them being empty in the future?

**Comment by inghamn** [comment]
Populating the lastchangeddates on these records fixed the problem with search.  It might be worth looking into additional restrictions on database fields to better facilitate batch import or other out of band processes.

**Comment by bobintetley** [comment]
It would, I can't understand why we didn't make them NOT NULL to be honest and it's an easy fix to do that as it's only in one place. I've checked back to ASM2 and they're marked NOT NULL in ASM2 so I have no idea why they're nullable in 3. I'll add a fix for that to new databases. 

You're right that older versions of MySQL used to store null dates as 0000-00-00 instead of a genuine NULL, so maybe that's how it never triggered before. I vaguely remember you used to have to have the driver translate them to null though.
