### ISSUE TITLE
Publishing log timestamps off by an hour

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#402]
It doesn't appear that the log times are taking into account the correct timezone and daylight saving time.  The datetime returned by the OS was 9:51, but it is displayed in the Publishing log as 8:51

**Comment by bobintetley** [comment]
Nope, they don't. DST is an enormous can of worms I didn't fancy opening. The only workaround is to change your timezone offset under Settings->Options when you enter/leave daylight savings.

**Comment by inghamn** [comment]
I would recommend storing UTC in the database, and converting it to local time in python during the HTML rendering.  It's what I use for all our web applications.  

I know postgres also supports timezones, but that could cause confusion when migrating data.

**Comment by bobintetley** [comment]
Yep, that's the usual standard way. Unfortunately, some of our pre-2000 database design is still showing and times are stored as local time in the database as they have since v1. We do it backwards and expect the server clock to be on UTC so we can apply a local time offset when calculating and storing dates. Fixing this would be a *huge* job as it would require changing every timestamp field in the database!
