### ISSUE TITLE
Move sitedefs configuration out of source directory

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#404]
When doing updates and automated installations, it is nice to have all the configuration and saved data outside of the installed application directory.   That way, an upgrade means simple deleting directory for the current version and copying the directory for the new version.

All of the site's settings, cache, and media would be safely in some other directory on the server's hard drive.  For our Ansbible control, we put this in /srv/data/asm.  The path to the configuration file could be set as an environment variable in the WSGI or some other convenient means.

**Comment by bobintetley** [comment]
That's a really good suggestion.

**Comment by inghamn** [comment]
When implementing this, the new configuration file should probably not be python, but instead, some hash format, like .ini

The challenge is in using automated deployments.  The deployment system (ansible, chef, puppet, etc) will need to set values in this file per server that it's deployed to.  Ansible can easily update values in an INI file, but editing raw python code using regular expressions becomes problematic.

**Comment by bobintetley** [comment]
sitedefs.py is a HUGE pain for anyone upgrading as well. Rather than ini, I'd probably go with the standard UNIX style config file format (not like there's much difference, just no section headings).

# Comments 
A=B
X=Y
Z = { "A": "B", "C": "D" }

We can use JSON parsing on the values where lists and dictionaries are expected.

I'd keep sitedefs.py as it's heavily referenced and useful in its current form. But, instead of hard coded values living in there though, they'd all be calls to another library that read the value from a config file. 

As is convention, that library would check for the config file at $HOME/.asm3 and then fall back to /etc/asm3.conf 

The calling code in sitedefs.py could optionally supply a default value in case one is not found in the config file. This would make life *much* easier for people upgrading and would allow for straightforward package upgrades without everything falling over afterwards due to missing sitedefs.

(Note for RRT - this would break the current /dev system in place on production servers).

**Comment by inghamn** [comment]
A default location for the config makes sense; however, it would be nice to provide a way for deployers to declare where the config file is.  An Environment variables set in the WSGI file might do the trick.

Typically, with our application deployments, we prefer to have all the non source code stuff (config, data, cache, etc) in a single place.  Then we have the source code somewhere else.  This means when upgrading, we can delete the source directory, replacing it with the new version.  All our config and data remains.  This simplifies upgrades.  Also, if config and data is outside of source, then it doesn't get committed to the git repository.

**Comment by bobintetley** [comment]
It's a possibility, though it has some potential issues. https://gist.github.com/GrahamDumpleton/b380652b768e81a7f60c

I'd suggest we test for the following in order to locate the config file:

1. Look for a path to a file in an environment variable called ASM3_SITEDEFS (should be able to set it via Apache2 envvars if you want to do this)
2. Look for $INSTALL_DIR/asm3.conf
3. Look for $HOME/.asm3
4. Look for /etc/asm3.conf (the Debian package will be setup to create this by default)
5. Use the default value if no file was found (we also use the default value if it is not present in the first file we did find)

As you say, the /etc file means you can just unpack a new release over the old to upgrade.

**Comment by inghamn** [comment]
All of that stuff typically what I expect in a WSGI file.  I think the confusion is ASM doesn't have a seperate WSGI file, but instead the source code *is* the WSGI file.  I guess I'm used to using a WSGI file as the entry point for the app.  The deployer person would write the WSGI file according to whatever their situation is.

For instance:
https://docs.ckan.org/en/2.8/maintaining/installing/deployment.html
(Not that CKAN's a model of good design....but the approach to a wsgi file is useful)

Since it's up to the sys admin to write the WSGI file according to their deployment, there's no need for any EVN variables to be set in the Apache conf.  Plus, automation (ansible, chef, puppet) can write the wsgi file as needed.

**Comment by bobintetley** [comment]
Yes, you're right - web.py kind of does it in what is now a non-standard way. I guess part of that is because web.py is old enough that wsgi hadn't "won" and it supports adapters other than wsgi (such as fcgi and mod_python) and partly because development of it stalled due to the death of the main developer.

Would the proposal for a conf file you can select via an env var or in a known place in /etc work for you?

**Comment by inghamn** [comment]
Yes, of course. That would work well for us, too.

**Comment by inghamn** [comment]
Setting the ENV in apache conf is functionally just fine; so, I don't know if the wsgi file solution is worth the priority.

Where it makes a difference, I think, is that if you relied on a separete wsgi file as part of the deployment, then you wouldn't need to write code to look in all these various places for the config file.  The config file location would always be declared in one place.

But, it certainly works either way.  Whichever way is easiest to implement is probably the correct choice.

**Comment by bobintetley** [comment]
It's certainly possible - all we need to do is add a method to code.py to return the application object so that it can be declared globally in the wsgi file as per the spec. Your wsgi file is then as simple as:

    sys.path.append("/usr/lib/sheltermanager3")
    # Set env vars here if you want
    import code.py
    application = code.get_wsgi_application()

From a difficulty to code perspective, we're only talking about the location of the config file which is pretty trivial and just a few levels of os.path.exists

I think I'm going to get this into 41 and go ahead with the plan outlined above (envvar, fallbacks, etc). I'll also add the get_wsgi_application() method to code.py so that you can use a separate WSGI file if you do want to and we'll ship a default wsgi file for those people that want to use it.

**Comment by bobintetley** [comment]
Realised we don't need the method at all, you should be able to do:

    import code
    application = code.application

**Comment by bobintetley** [comment]
I've commited a version of it working now. If you look in scripts/asm3.conf.example you can get an example config (it's basically sitedefs as it was but with lower case values and no string delimiters, boolean values are lower case to match json).

You can set an ASM3_CONF environment variable or (in order) $INSTALL_DIR/asm3.conf $HOME/.asm3 /etc/asm3.conf

**Comment by inghamn** [comment]
Cheers!  I'll check it out

**Comment by inghamn** [comment]
This is probably a case of me not understanding wsgi and python well enough...but I'm not able to get the lastest version working.

I'm having trouble setting the conf file location using an environment variables set in the apache conf.  Variables that are set in Apache using SetEnv do not come in to os.environ.  Rather, they come inside the environ variable passed to the application. So, for me, the os.environ['ASM3_CONF'] is never set.

https://modwsgi.readthedocs.io/en/develop/user-guides/configuration-guidelines.html#application-configuration

```apache
WSGIScriptAlias / /srv/sites/asm/src/code.py/
Alias /static /srv/sites/asm/src/static
AddType text/html .py
SetEnv ASM3_CONF /srv/data/asm/asm3.conf

<Directory "/srv/sites/asm/src>
    Options FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
```

I also tried writing a separate WSGI file to import code.py, but was not able to use code.py as a WSGI application.
```python
import os, sys
sys.path.append("/srv/sites/asm/src")
os.environ["ASM3_CONF"] = "/srv/data/asm/asm3.conf"
import code
application = code.application
```

```txt
mod_wsgi (pid=2170): Exception occurred processing WSGI script '/srv/data/asm/wsgi/asm3.wsgi'.
Traceback (most recent call last):
  File "/srv/data/asm/wsgi/asm3.wsgi", line 5, in <module>
    application = code.application
AttributeError: 'module' object has no attribute 'application'
```

**Comment by bobintetley** [comment]
My knowledge of WSGI/Apache isn't that great either. For SetEnv to work, you need mod_env enabled - do you have that? In Debian based distros you'd do "a2enmod env".

I'm not 100% sure whether SetEnv will work in this regard with WSGI, it's supposed to with CGI and SSI.

You could also look at setting it in /etc/apache2/envvars instead, which looks a shell script that's run to set variables before the process starts. It'd be something like:

export ASM3_CONF=/srv/data/asm/asm3.conf

The failure of your wsgi file is interesting. I think it's a path order problem - it's doing sys.path.append and putting our python modules as the last item on the path. There's a built in python module called code earlier in the path so you're getting that one instead of ASM.

Try inserting ASM as the first path element in your WSGI by doing this instead of sys.path.append

sys.path.insert(0, "/srv/sites/asm/src")

I just tested that in an interpreter from another directory and it seemed to work.

**Comment by bobintetley** [comment]
Let me know if you get the SetEnv approach working as that looks to be the most convenient to me!

**Comment by inghamn** [comment]
Thanks for the help with the path.  I've been able to get it working using a wsgi script to set the os.eniron variable.

I looked deeper into the SetEnv technique, and I don't believe it will ever work with the webpy framework.  Webpy never reads the environ from apache, and it's too late by the time it hands it off to code.py.  Setting an OS level environment variable doesn't really work for us, as it does't allow for running multiple instances of asm on the same machine at different URLs.

I will send a commit to #538  with the ansible changes to deploy it with a wsgi script.

**Comment by bobintetley** [comment]
os.environ is just a copy of the environment variables the python process received when it was spawned. I don't think webpy has anything to do with it. 

As long as SetEnv takes effect before Apache spawns a Python process (via mod_wsgi) then in theory it should work. It probably doesn't though, but I'll do a bit of investigation as it could simplify my deployment scripts.
