### ISSUE TITLE
Conditionals/loops in document templates

### ISSUE THREAD

**Issue by CodyJung** [bobintetley/asm3#428]
We have a couple of documents that have tables of (i.e.) medications. One of them has a table with 15 rows (MedicalName1, MedicalName2, ...) even though _most_ cats only use maybe 5-6. It ends up being a lot of wasted space when we generate a PDF, but we need to have enough rows to handle the medical information for those cats who have been at the shelter for a long time.

I realize that this is maybe a little much to ask from a templating engine, but is there a way to either loop over a list of WordKeys or conditionally hide html based on whether a value is populated?

**Comment by bobintetley** [comment]
Wordkeys become empty strings when they aren't populated. The only reason it's still wasting space I guess is because you have your items in table cells with fixed sizes. If you use <br/> tags between rows they become empty whitespace that will be suppressed by the browser, but it means you can't use tables to layout the data. Similarly, table cells without any content or borders will be suppressed if they don't have a fixed size and are empty.

I think conditionals and loops are outside the scope of templates. 

There are also various reports that print medical history and one way to get what you need might be to implement it as a report instead - you can certainly use conditionals and loops in the report HTML section via javascript and there can be a lot done with SQL too.
