### ISSUE TITLE
Some tips and tricks are not translated

### ISSUE THREAD

**Issue by julian-poidevin** [bobintetley/asm3#864]
I found some tips and tricks are not translated :
![image](https://user-images.githubusercontent.com/8756421/84594199-ee7ce280-ae50-11ea-8b36-1aa0bd2cd8b0.png)

This sentence is translated :
https://github.com/bobintetley/asm3/blob/60ade5447134d749a2ac22c2b4f4ddbd769d4ae7/po/fr.po#L14033-L14040

https://github.com/bobintetley/asm3/blob/daf7c687b6d85a860395923f34fe508393d5d800/src/asm3/locales/locale_fr.py#L3300

https://github.com/bobintetley/asm3/blob/daf7c687b6d85a860395923f34fe508393d5d800/src/static/js/locales/locale_fr.js#L3300

**Comment by bobintetley** [comment]
This looks like a problem with the textwrap library that our script is using to generate the pot file. Some of the tips using a dash to separate menu items, eg: Settings-Options-X 

The textwrap library thinks its ok to break on the dash and put a space after it. This has the effect of changing the key so that you can no longer use the English text to resolve the translation. 

Rather than faff around with textwrap, I've just changed them to commas since the dashes don't look great anyway and regenerated the asm.pot. It should allow you to translate those strings now.
