### ISSUE TITLE
Licensing Renewal bugs

### ISSUE THREAD

**Issue by headhunter911** [bobintetley/asm3#949]
**Describe the bug**
Confirmed bugs on latest demo
Bug:
Renewal links send you to two different renewal forms, you can not renew license with either form if you use the same license Number 
**To Reproduce**
Create a person A 
Create a license Number 001 for person A
From MENU goto ASM-->Animal Control-->License Renewal
Select Person A (note past license do not show up for that person)
Try to renew license number 001 with new dates
Receive error License Number 001 already exists
Now you can also go to ASM-->Animal Contol-->Licensing
Select appropriate license for person A, select renewal and get same result

**Expected behavior**
Either old entry change status to expired or renewed and new entry with same license number shows with new expiration. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] reproducible on your demo site

**Comment by bobintetley** [comment]
Hi, thanks for reporting. The licence renewal functionality creates a new licence record for that animal and person for the period specified. 

By default the system will not let you create a new licence record with the same number as a previous licence. 

You can turn this off in a live system with Settings->Options->Animal Codes->Allow duplicate license numbers

Options are not available in the demo since they could be used to break the demo for others.
